platform :ios, '15.0'

use_frameworks!
use_modular_headers!

target 'iosApp' do
  # KMP shared module
  pod 'network', :path => '../network'
  pod 'Reachability', '3.2'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end